### ISSUE TITLE
Same "sysmonShell.exe" is the executable in the SysmonShell and SysmonView XX.zip files.

### ISSUE THREAD

**Issue by pblahman** [nshalabi/SysmonTools#12]
I downloaded the 64.zip and 32.zip files for sysmonshell and sysmonview.    All of the zip files contain a file named sysmonShell.exe.    I did not find an executable named sysmonView.exe.    Am I making an incorrect assumption that there should be a sysmonView.exec?

**Comment by josephbleroy** [comment]
I have the same issue. Sysmonview doesn't exist - the only files uploaded are sysmonshell.

**Comment by nshalabi** [comment]
Fixed, thank you.
