### ISSUE TITLE
Sysmon View - Not loading Network Map

### ISSUE THREAD

**Issue by TrueCitrus** [nshalabi/SysmonTools#19]
I have configured Sysmon View with my IPstack API key and chose to geolocate IPs during the Sysmon XML import however I do not see any data in the Map View. I see a bunch of Network Connection detected events within my Sysmon log yet not a single entry is listed on the map. I logged in to my IPStack account and can see zero API requests for my account. It also looks like it's not pulling any info from VirusTotal either. What am I doing wrong? How can I get Sysmon View to properly show the map data and VirusTotal info?

**Comment by nshalabi** [comment]
Thank you and apologies in responding back,

Could you kindly send me an email to nader@nosecurecode.com to work on re-producing the issue,

Much appreciated your support

**Comment by nshalabi** [comment]
Fixed and uploaded the new version, much appreciated the feedback.
