### ISSUE TITLE
[Feature Request/SysmonShell] - Support for Sysmon Schema 3.40

### ISSUE THREAD

**Issue by woifi** [nshalabi/SysmonTools#3]
Hi,

your work looks great but it seems that it does not support the current sysmon schema 3.40. I was wondering if you plan to release an updated version that would support 3.40?

Thanks,

woifi

**Comment by nshalabi** [comment]
Hi woifi,

Can you please elaborate more on "it seems that it does not support the current sysmon schema 3.40"? Where did you spot that exactly?

Much appreciated

**Comment by nshalabi** [comment]
The tool is updated to support the latest schema, thank you for reporting.
