### ISSUE TITLE
[bug] Both 32 and 64 bit of SysmonShell are actually SysmonView

### ISSUE THREAD

**Issue by lctrcl** [nshalabi/SysmonTools#4]
Hi,

I think this was an unintentional mistake, but if you download SysmonShell from current commit (8bc3ce0b0cdd9133f7b8e1fffe27d614e37b4b45), it's actually expanding to sysmonview in both cases. P

**Comment by nshalabi** [comment]
Yes you are right, thank you for reporting, I have just re-uploaded. Too much automation :)
Can you check and let me know please to resolve the issue?

Much appreciated,

**Comment by lctrcl** [comment]
Yes, now everything seems fine. Cheers
