### ISSUE TITLE
[Feature Request/SysmonShell] - Support for Sysmon Schema 4.00

### ISSUE THREAD

**Issue by stdio-h** [nshalabi/SysmonTools#5]
Thanks for your work. Is there yet another plan to release an updated version supporting Schema 4.00?

Sysmon v7.0 (published on January 2, 2018) uses Sysmon Schema 4.00 and is no longer compatible with current output version 3.40:

```
Loading configuration file with schema version 3.40
Sysmon schema version: 4.00
Error: Incorrect or unsupported schema version 3.40. Current Sysmon schema version 4.00
```

Thanks,
-Roland.

**Comment by nshalabi** [comment]
Thanks,

Working on it, will update soon.

Much appreciated

**Comment by nshalabi** [comment]
Done!
