### ISSUE TITLE
Virus/Trojan

### ISSUE THREAD

**Issue by Themercee** [nshalabi/SysmonTools#7]
https://www.hybrid-analysis.com/sample/840a155df13b88cad1172372d80a97ebfb9a0a9a33c7d5baf6890e84d122fa16/5acf838b7ca3e103f004dc13

There is a lot of indicators about Malware. Could be nice to have sources to help people collaborate with and ensure no backdoor are in it.

**Comment by nshalabi** [comment]
Thank you,
I responded on hybrid-analysis, please note that the indicators are referring to the packed nature of the tool, as mentioned in the readme file.
Much appreciated your feedback
